version: 2

jobs:
  tests:
    docker:
      - image: python:3.7

    steps:
      - checkout
      - run: pip install tox
      - run: tox
      - store_test_results:
          path: test-report.xml

workflows:
  version: 2
  build:
    jobs:
      - tests
