version: 2

jobs:
  tests:
    docker:
      - image: python:3.6

    steps:
      - checkout
      - run:
        name: Install requirements
        command: pip install tox
      - run:
        name: Run tests
        command: tox

workflows:
  version: 2
  build:
    jobs:
      - tests
