version: 2

jobs:
  tests36:
    docker:
      - image: python:3.6
    working_directory: ~/django-grpc
    steps:
      - checkout
      - run: pip install tox
      - run:
          name: Run tests
          command: tox
      - store_test_results:
          path: test-report.xml
  tests37:
    docker:
      - image: python:3.7
    working_directory: ~/django-grpc
    steps:
      - checkout
      - run: pip install tox
      - run:
          name: Run tests
          command: tox
      - store_test_results:
          path: test-report.xml
  tests38:
    docker:
      - image: python:3.8
    working_directory: ~/django-grpc
    steps:
      - checkout
      - run: pip install tox
      - run:
          name: Run tests
          command: tox
      - store_test_results:
          path: test-report.xml
  tests39:
    docker:
      - image: python:3.9
    working_directory: ~/django-grpc
    steps:
      - checkout
      - run: pip install tox
      - run:
          name: Run tests
          command: tox
      - store_test_results:
          path: test-report.xml

workflows:
  version: 2
  build:
    jobs:
      - tests36
      - tests37
      - tests38
      - tests39
